#################################################################
###################### NexT Configuration #######################
#################################################################

# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

custom_file_path:
  sidebar: source/_data/sidebar.njk
  footer: source/_data/footer.njk
  variable: source/_data/variables.styl
  style: source/_data/styles.styl


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini

darkmode: true


# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

creative_commons:
  license: by-nc-sa
  sidebar: true


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  home: / || fa fa-home

  # about: /about/ || fa fa-user

  tags: /tags/ || fa fa-tags

  categories: /categories/ || fa fa-th

  archives: /archives/ || fa fa-archive

  #schedule: /schedule/ || fa fa-calendar

  #sitemap: /sitemap.xml || fa fa-sitemap

  # commonweal: /404/ || fa fa-heartbeat

menu_settings:
  icons: true
  badges: true


# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

avatar:
  url: /images/谭国永.JPG
  rounded: true

social:
  GitHub: https://github.com/guazilalala || fab fa-github
  E-Mail: mailto:guazilalala@hotmail.com || fa fa-envelope
  # RSS: /atom.xml || fa fa-rss
  # Gitter: https://gitter.im/hexo-next || fab fa-gitter

social_icons:
  enable: true
  icons_only: true
  transition: true

toc:
  enable: true
  number: true
  wrap: true


# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2020
  icon:
    name: fa fa-heart
    animated: true
    color: "#808080"
  copyright: Wing
  powered: false


# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

post_meta:
  updated_at:
    enable: false

symbols_count_time:
  separated_meta: true
  item_text_total: true

post_edit:
  enable: false
  url: https://github.com/next-theme/theme-next-docs/edit/master/source/


# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

mobile_layout_economy: true

codeblock:
  theme:
    light: default
    dark: tomorrow-night
  copy_button:
    enable: true
    style: default

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

github_banner:
  enable: true
  permalink: https://github.com/guazilalala
  title: Follow me on GitHub


# ============================================================= #
# ======================= SEO Settings ======================== #
# ============================================================= #

index_with_subtitle: true

exturl: true

google_site_verification: 5AUIVYTbHIAuz-eQtxSfZbWW5eg9_EVZMSQycIuXrG0


# ============================================================= #
# =============== Third Party Services Settings =============== #
# ============================================================= #

math:
  mathjax:
    enable: true

pjax: true

mediumzoom: true


# ============================================================= #
# =================== Comments and Widgets ==================== #
# ============================================================= #

comments:
  lazyload: true

disqus:
  enable: false
  shortname: next-theme
  count: true


# ============================================================= #
# ================= Statistics and Analytics ================== #
# ============================================================= #

# google_analytics:
#   tracking_id: UA-108155018-3
baidu_analytics: c7b61fe1cd6ac6a0909fcfe1e562f210

busuanzi_count:
  enable: true
  total_visitors: false
  total_visitors_icon: fa fa-user
  total_views: true
  total_views_icon: fa fa-eye
  post_views: true
  post_views_icon: far fa-eye


# ============================================================= #
# ====================== Search Services ====================== #
# ============================================================= #

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  style: simple
  icons: true
  light_bg_offset: -3

tabs:
  transition:
    tabs: true
    labels: true

mermaid:
  enable: true


# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #

motion:
  async: true

vendors:
  internal: jsdelivr